### ISSUE TITLE
Error message

### ISSUE THREAD

**Issue by 123456789096543a** [MikeshCZ/zscaler-killer#1]
did all the steps and got this error
<img width="394" alt="Screenshot 2024-12-18 181424" src="https://github.com/user-attachments/assets/cbe59053-23c5-4cb1-b6e9-f844dd11c510" />

**Comment by MikeshCZ** [comment]
> did all the steps and got this error
> 
> <img width="394" alt="Screenshot 2024-12-18 181424" src="https://github.com/user-attachments/assets/cbe59053-23c5-4cb1-b6e9-f844dd11c510" />
> 
> 

If you click on ´More info´ at the end of the text then you will see the button ´Run´ below.

**Comment by MikeshCZ** [comment]
You can also try newer version written in C++ with GUI. https://github.com/MikeshCZ/ZSAkill

**Comment by 123456789096543a** [comment]
> > did all the steps and got this error
> > <img alt="Screenshot 2024-12-18 181424" width="394" src="https://private-user-images.githubusercontent.com/192075834/396799730-cbe59053-23c5-4cb1-b6e9-f844dd11c510.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ5NjA1NTYsIm5iZiI6MTczNDk2MDI1NiwicGF0aCI6Ii8xOTIwNzU4MzQvMzk2Nzk5NzMwLWNiZTU5MDUzLTIzYzUtNGNiMS1iNmU5LWY4NDRkZDExYzUxMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyM1QxMzI0MTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kZGU2MTcxOTExNTRkMjI0NzA3NzRlOTBmNTE1NjhiNTM5NWQ5MDg1MzM4MGRmYTIzNGVhNzFmODRlYmIyMjc5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.r8mRDpfwfz4zukkg56F8Iti1Citq90ncq7Ty5VY62pc">
> 
> If you click on ´More info´ at the end of the text then you will see the button ´Run´ below.

thanks but i still got this error
<img width="677" alt="Screenshot 2024-12-24 002527" src="https://github.com/user-attachments/assets/1a9227bb-3fc0-460e-b162-f5b70d361a45" />

**Comment by MikeshCZ** [comment]
As is mention in README.md:

`You need to run this batch file as administrator to give the script file rights to process taskkill command successfully. Usually, you can do it by right click on the ZSA_kill.bat file and choose Run as administrator from menu.`

Hope this will help you.
